### ISSUE TITLE
Bug opening new tab when using 2 monitors

### ISSUE THREAD

**Issue by gabrielmulle** [joelshepherd/tabliss#1]
**Context**: I'm using a Mac and Firefox Developer Edition 57.0b5 (64-bit), Tablis 1.2.1, last updated Oct 04, 2017. I'm using another monitor connected to this Mac.

**Problem**: When opening a new tab in this second auxiliary monitor, I cannot start typing right away because the cursor is not automatically in the address bar. I have to click the address bar to start typing.

However, when opening a tab in the Mac, this problem doesn't exist as the cursor is already automatically in the address bar.

Thanks
Gabriel

**Comment by joelshepherd** [comment]
Interesting. I'll see if I can replicate this when I get back to my multi-monitor setup next week.
Do you have the search box widget activated by any chance?

**Comment by gabrielmulle** [comment]
Hi Joel, 
No, I do not have the search box, I use the address bar to search.
Thanks for this amazing add-on.

**Comment by joelshepherd** [comment]
I have not been able to replicate this on my macbook. The cursor seems to be in the address bar on both my macbook and extra monitor.

Firefox Developer Edition has since updated to beta-8, so it might have been a bug in an earlier beta of Firefox? The only other thing I can think of is if Tabliss is conflicting with another Firefox add-on or Mac window/screen manager.

**Comment by gabrielmulle** [comment]
Hi Joel, 
Indeed the problem is fixed. I think you're right, it was probably a FF bug. Now the FF version is 57.0b8 (64-bit), it updates very fast.
