### ISSUE TITLE
[Suggestion] Add Opera browser compatibility

### ISSUE THREAD

**Issue by Hanif1601** [joelshepherd/tabliss#108]
Hey, can you port this or release for Opera browser? Recently I tried to install and run Tabliss on Opera Beta on my PC and the browser itself won't to run this extension. Please, **PLEASE** port this extension or release an new Tabliss for Opera (because Opera currently Chromium-based or Chrome based).

**Comment by trickypr** [comment]
Why do you need this? I work on Safari on occasion and there is no add-on for that. That doesn't mean that I don't use it. There is a [web](https://web.tabliss.io/) version. The only thing that the add-on does is makes it easier to install and somewhat more offline (loads faster).

**Comment by joelshepherd** [comment]
Opera is indeed built on Chromium. However when I last looked into it (and seems still to be the case), the Opera devs specifically disallow overriding of the new tab page.

I am not exactly sure why, but if I had to guess, I would say they receive some sort of kickback from the items they put on their speed dial. I can't imagine they would be fond of a free, open source extension taking those revenue streams away.

While there are various hacky ways around the restriction, I do not particularly want to hack around the wishes of the Opera devs. Though Tabliss is open source, so you could try and implement some of these hacks yourself ;)

Closing for now though, because unless the Opera devs remove the restriction, I won't be officially supporting an Opera port sorry. If you are looking for a nice, non-Google integrated, Chromium based browser - why not try direct Chromium builds (Chrome without Google's proprietary layer): https://chromium.woolyss.com/
