### ISSUE TITLE
Make the Search Box follow the browser's search engines

### ISSUE THREAD

**Issue by aurora-of-earth** [joelshepherd/tabliss#114]
The Search Box doesn't provide the user added browser-wide search engines.

**Comment by joelshepherd** [comment]
When I added the search box there was no way to get the browser's search engines. It seems that since then, Firefox have added support for it, but it's not available on Chrome yet: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/search

While I won't to add permissions to Tabliss (the search API requires a permission), I will consider it once Chrome has support. I'll close it for now, but can reopen this once Chrome supports the search API too.
