### ISSUE TITLE
Using the real override config for the start page config

### ISSUE THREAD

**Issue by aelisya** [joelshepherd/tabliss#116]
I allow myself to contact you because I noticed that you were proposing a manual modification of the home page while firefox offers a function to change the home page from an extension.

"chrome_settings_overrides" : {
    "homepage": "link"
  },

I hope it will in the next changelog ^^

**Comment by joelshepherd** [comment]
Tabliss actually used to control the homepage, but it was removed after I got one too many emails with people complaining viciously that Tabliss wasn't letting them use their homepage.

You can see the change in the changelog already :(
https://github.com/joelshepherd/tabliss/blob/master/CHANGELOG.md#1140---2018-07-10

I have since had many (less aggressive) requests asking Tabliss _to_ control the homepage once more.

The best solution would be for Firefox to provide a built-in way to choose whether an extension controlled your homepage or not. Rather than just the "all or nothing" approach it currently has where you can only disable the extension to stop if from controlling your homepage.

At this time I won't be changing it, but I would happily accept if someone found a smoother way of letting the user choose for Tabliss to takeover the homepage!

**Comment by aelisya** [comment]
You can use it, and add a settings this settings will redirect on the home page (chosen in the tabliss config) or the new tab ?

**Comment by trickypr** [comment]
This code needs to be part of the add-ons manifest. As far as I can tell from looking through Mozilla’s docs, you can’t change this in the add-one code. If there is a way to do it, then we might be able to do something.
