### ISSUE TITLE
Expand collections idea for Unsplash - rotation between collections

### ISSUE THREAD

**Issue by Smile4ever** [joelshepherd/tabliss#135]
It would be nice if you could put multiple collections in the "custom" field.

For example if I want to rotate between these collections:
https://unsplash.com/collections/1053828/tabliss-official
https://unsplash.com/collections/62890/into-the-wilderness

I would be able to put 1053828,62890

**Comment by joelshepherd** [comment]
Funnily enough, your suggestion may actually work already. 

Because the Unsplash API actually accepts a comma-separated list of collection IDs (https://unsplash.com/documentation#get-a-random-photo), and Tabliss just interpolates your collection ID(s) into the API parameters (https://github.com/joelshepherd/tabliss/blob/master/src/plugins/backgrounds/unsplash/api.ts#L18).

I gave it a brief try and it seems to work! Ironically the large size of Tabliss's Official collection hinders your results here, because its much more likely to choose an image from Tabliss's collection than the other, 6 times smaller, collection.

Seems to work the same for you?

**Comment by Smile4ever** [comment]
Yes, thank you. Great news 👍 

I verified with 4807737,2129330 since they're small collections so it's easy to see which photo comes from which collection.

To increase the chance of another collection than the Tabliss official one, you can put the same collection id multiple times:
1053828,62890,62890,62890,62890

**Comment by Smile4ever** [comment]
For now I've settled on 1286209,62890,225,827743

**Comment by joelshepherd** [comment]
Great to hear!
