### ISSUE TITLE
[Feature Request] Firefox Multi-account container compatibility

### ISSUE THREAD

**Issue by NourEddineX** [joelshepherd/tabliss#144]
Hello,

I use firefox with official Mozilla's Firefox [Multi-account containers add-on](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers)

Tabliss custom settings doesn't load on new container tab
please add support to it.

Thank you

**Comment by trickypr** [comment]
This issue has already exists: #92 

The way that the multi-tab container works is that it separates tabs into containers. These containers stop all of the websites that you open from assessing data that is stored inside another container. This includes indexdb, the system used for storing tabliss' settings. This means that in different containers, tabliss can't assess it's settings. One potential way of solving this problem is by using the [extension storage api](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage). The change to this api has problems in its self (see #69). While this issue is only with the sync part of the api, we may still run into some of the same road blocks.

**Comment by NourEddineX** [comment]
I see,
I hope tabliss development team can use the extension storage API.
Since this issue already exists on #92 as you mentioned, I'm closing my issue

**Comment by joelshepherd** [comment]
FYI, I'm working on it 🙂

**Comment by DiegoRealpe** [comment]
Any updates?

**Comment by joelshepherd** [comment]
Yep, this is complete and been release for... a year maybe?
