### ISSUE TITLE
import export option for the settings

### ISSUE THREAD

**Issue by mywayfr** [joelshepherd/tabliss#165]
Thanks a lot for this great work, without tracking settings!
Please include if possible a import export option for the settings.
Even with FF sync all the settings are lost when using an other device or in HDD crash.

Cheers from Belgium :)

PS: mail server at "feedback@tabliss" return reach error.

**Comment by joelshepherd** [comment]
Good news! Firefox account sync is coming in the next version of Tabliss in the next few weeks!

I will leave this issue open though, because I may add a direct import/export sometime in the future.

(PS: the address is feedback@tabliss.io - which seems to work for me?)

**Comment by hypnomaki** [comment]
I would highly appreciate this!

A Synchronization Feature via the native Browser Sync is also nice but I installed tabliss because its open source and doesn't force me to login somewhere else so please don`t add a mandatory sync across browsers.

I can live with the native Firefox sync but I don't use the same profile across home & work. Also I use different browsers. That's exactly why an import/export feature would be awesome - it keeps up the high trust standards and is not limit productivity that much!

**Comment by ZonK256** [comment]
Will this export/import option also include todo list? It would be awesome!

**Comment by ChrisLane** [comment]
@trickypr said in #238 
>Tabliss has a function where you can sync settings across different devices using a firefox or google account. It would be an interesting feature in terms of sharing configs.

Does this feature actually exist yet? I don't see any options for synchronising and just signed in to Firefox on a new computer and saw that none of my tabliss settings had been synchronised.

**Comment by referi** [comment]
It's unusable without export/import settings function

**Comment by joelshepherd** [comment]
This was added last year in 2.1.0
