### ISSUE TITLE
Tabliss does not appear to be saving settings in Firefox

### ISSUE THREAD

**Issue by APerson4645** [joelshepherd/tabliss#176]
I just downloaded Tabliss and am attempting to use it but it doesn't save settings with a New Tab. I can change the background in one tab and the time settings and it doesn't switch that over to another tab nor load it into any other new tabs I open.

What does stay: Widgets, timezone, and language
What doesn't stay: Font settings, widget settings, background settings (partially, what type of background "solid color;dribble;upload image;etc. does stay but the background itself does not stay), time settings, and greeting message

It appears to stay when using the website itself but not when using the extension and new tabs.

**Comment by APerson4645** [comment]
What does stay: Widgets, timezone, and language
What doesn't stay: Font settings, widget settings, background settings (partially, what type of background "solid color;dribble;upload image;etc. is saved but the background itself will not be saved), time settings, and greeting message

**Comment by APerson4645** [comment]
After giving it some time the time settings and greeting message (and presumably font settings and widget settings) do stay but the background doesn't

**Comment by mikekok** [comment]
Same goes for Brave browser.
The Quick Links and Todos widgets' settings are not saved.

**Comment by AntoineSebert** [comment]
I had a similar problem; recently switched from Firefox Nightly to Firefox Developer.
The auto sync goes without any problems, and Tabliss is automatically added, but the Quick Links are not there.
Is it at least possible to import them manually, given the Tabliss' storage file location ?

**Comment by ndbroadbent** [comment]
This is also happening in Chrome 78.0.3904.108 on macOS Catalina. It doesn't save the settings when try to set "Show a new photo" to "every 15 minutes".  And the default "every new tab" doesn't seem to be working, because it's been stuck on a picture of some deer for over 24 hours:

<img width="1268" alt="Screen Shot 2019-12-01 at 1 48 56 AM" src="https://user-images.githubusercontent.com/139536/69904738-ca8a1000-13dc-11ea-82d2-71cc31461306.png">

**Comment by tuxedocat** [comment]
Same here, with Chrome 79.0.3945.79 on macOS Catalina.
Changes applied to the widgets don't seem to be saved into the storage (indexedDB), from a quick look through Chrome's DevTools.

**Comment by joshuabeny1999** [comment]
Issue also appears on Brave 1.2.43 Chromium: 79.0.3945.130 and Tabliss

**Comment by joelshepherd** [comment]
Hey guys, I have rewritten the setting storage mechanism in the upcoming Tabliss 2. Once it is out let me know if these issues go away!

**Comment by codewing** [comment]
I would gladly beta test if you need any help :)

**Comment by gringofe** [comment]
For me, setting saving used to work just fine, but since Tabliss 2 it seems to be broken. :(

**Comment by APerson4645** [comment]
@joelshepherd Seems to work now perfectly for me, but @gringofe appears to be having issues so I'm not going to close the issue for now.

**Comment by Aravisian** [comment]
I am also having this issue on Zorin 15.3 (Ubuntu 18.04 Derivative) running FF 83.0 as of 11 Dec 2020
I have homepage set to Tabliss. Sometimes new tab shows the tab background image consistently, until I close FF and reopen it later. Sometimes, it seems to forget it during use.

**Comment by mooror** [comment]
I can confirm that this is still a problem in Firefox 84.0.2 (64-bit) on Windows 7.

Just uploaded several files. Opened the tabs a few times, everything seemed to work. A few minutes later I open a new tab the custom uploads are all gone from the "Upload Images" section

**Comment by NJeyyy** [comment]
Same here, but I think I might know how to fix it when the tabliss extension is not saving the setting,i'ts not fix it I guess but it's just help you when the setting is reseted. you just need to export it and when it reset accidenttly, you can import it from the file(I just rather do that than do the setting all over again). But that can't save the image that you upload..   
It's just saving all widget and the setting,background display setting,the background(only in gradient color and solid color)
the thing that not saved: image that uploaded,the background(in Unsplash,giphy,and upload image)
CMIIW because I just found how to do this just several minutes ago...

**Comment by AltNoMatic** [comment]
Issue still not fixed (Windows 10 1909 Build 18363.1440 & WaterFox latest version)

I have to manually re-upload all the background images at least twice a week otherwise they don't work. I have tried following steps to try and fix the problem:

• Re-installing browser and extension
• Allowed all cookies, deleted browser cache and junk
• Disabled strict privacy mode

I can't think of any other methods to try and fix this problem. My other machine also seems to have the same problem.

**Comment by joshuabeny1999** [comment]
It also happening on Brave (Based on Chrome).

**Comment by Electromorphous** [comment]
So I am on the latest version of chrome on windows 10 and I was facing the same issue. Once restarted my tabliss settings were not saved on the chrome. But I checked some other extensions that might be stopping these settings from being saved and removed adobe acrobat from my chrome extensions and now tabliss settings are saved and it works normally.

**Comment by Electromorphous** [comment]
So I removed a few other chrome extensions that I didn't really need and tabliss seems to be working fine again.

**Comment by cantao** [comment]
Same on Firefox 91.0.2 on Archlinux.

**Comment by fcolecumberri** [comment]
librewolf 95.0.2 on Garuda, same thing

**Comment by joelshepherd** [comment]
Can follow along in: #268 
Potentially fixed
