### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by MrJJJ** [joelshepherd/tabliss#19]
Would be great to have a simple todo list à la momentum.

**Comment by joelshepherd** [comment]
This is (finally) the next item on my _todo_ list! 😂

I'm aiming for the next release.

**Comment by BrunoGomesCoelho** [comment]
Also looking forwards to it :)

**Comment by Smile4ever** [comment]
> Feel free to post any feedback in here

Edit functionality of todo items?

**Comment by BrunoGomesCoelho** [comment]
Thanks for the quick implementation!
Some small thoughts:

The option to edit a task would be nice;
I think left aligned tasks might look better;
Currently you can select negative values for "Default number to show" if you click on the down arrow which kind of bugs the system.

**Comment by joelshepherd** [comment]
Thanks for the feedback. I'll get in:
- Edit functionality
- Try left aligning the checkboxes (maybe make it an option?)
- Fix that negative bug!

I'll test out some UI ideas to see done items. I like the idea of multiple lists too, might add that in a future version!

**Comment by joelshepherd** [comment]
This feature should be out for everyone by now!

Some thoughts on using it for the first time at work today: I am definitely going to need the ability to reorder tasks and have a filter to display completed tasks! I will aim to add these in the next release.

Enjoy!

**Comment by Jackymancs4** [comment]
Hello @joelshepherd 
I'm a great fan of your work on tabliss!
If it's ok for you, I have prepared a little feedback for some UX aspects of the new TODO list widget.

### Before

| Compact | Expanded |
| -- | -- |
|  ![before2](https://user-images.githubusercontent.com/6209647/40990324-bed8c104-68f0-11e8-87fc-0568c8fde883.png) | ![before1](https://user-images.githubusercontent.com/6209647/40990325-befbc280-68f0-11e8-9c92-3b9e44a29729.png) |

 - When the TODO list becomes too long, it overflow the page.

A possible fix:

```css
.TodoList {
    max-height: 340px;
    overflow-y: auto;
}
```

```340px``` value was perfect for my resolution, but probably a percentage value is better for scalability.

 - When the left aligment setting is set, the add and expand/contract symbols seems awkwardly out of alignment

I would suggest to apply 
```css
text-align: left;
```
on ```TodoList``` class instead of ```Todo```

### After 

| Compact | Expanded |
| -- | -- |
| ![after1](https://user-images.githubusercontent.com/6209647/40990393-f36a926c-68f0-11e8-88d3-19a5ae170162.png) | ![after2](https://user-images.githubusercontent.com/6209647/40990395-f39df8dc-68f0-11e8-8a6c-b175ca2a3e59.png) |

---

- When the background is very detailed (and maybe whith a variety of little white areas) it get increasingly difficult to read the titles with ease.

My suggestion is to add a very slighly dark backgroud, something like:

```css
.Todo {
    text-align: inherit;
    background: rgba(50,50,50, 0.5);
    padding: 15px;
    border-radius: 15px;
}
```

(The background value definetely need some tweaks)

| Compact | Expanded |
| -- | -- |
|  ![afterafter](https://user-images.githubusercontent.com/6209647/40990421-157b920c-68f1-11e8-8e06-2418d48221ed.png) | ![before1](https://user-images.githubusercontent.com/6209647/40990630-bf127650-68f1-11e8-8af6-e6ec9e768844.png) |

**Comment by BrunoGomesCoelho** [comment]
Great update @joelshepherd !

Some considerations:

> I would suggest to apply
`> text-align: left;`
> on TodoList class instead of Todo

This was also what I had in mind when I suggested left-align :)

**Comment by joelshepherd** [comment]
Forgot to update this thread! I have (in last month's update) added the "completed" task filter, deleting existing tasks, and @BrunoGomesCoelho's left align suggestion :)

I am glad you guys like it!
