### ISSUE TITLE
Quick Links Name alignment issue in Tabliss 2.0

### ISSUE THREAD

**Issue by AshokRaja10** [joelshepherd/tabliss#214]
This is when I set 4 quick links per row. Its the name alignment is perfect as expected it is present adjacent to the icon.

However, if I increase the count to 5 per row, then the alignment is messed up. The name is no longer present adjacent to the icon.

This is the case when increasing the count higher than 5...

**Comment by joelshepherd** [comment]
Hello! I have just pushed a patch for this. I have also changed the alignment to left if you have more than 1 column so all the icons line up under each other.

Does this suit for you?

**Comment by AshokRaja10** [comment]
Yes.. That would work.

**Comment by AshokRaja10** [comment]
Please update here once the update patch is rolled out in firefox addon store.

**Comment by joelshepherd** [comment]
It has now been released on the Firefox store 🙂

**Comment by AshokRaja10** [comment]
Thank you..

**Comment by ChrisKar96** [comment]
Hello,

I was searching why my custom links where aligned to the left after I upgraded until I saw this answer.

> 
> 
> Hello! I have just pushed a patch for this. I have also changed the alignment to left if you have more than 1 column so all the icons line up under each other.
> 
> Does this suit for you?

This is not the behavior I expect, since all the other widgets I use are center aligned, like greeting, time etc. 
I use two rows of 3 links each and in the first row I only have icons without extra text, so seeing them aligned left is not aesthetically pleasing. 
I solved my problem with a custom css snippet:
.Links{
    text-align: center !important;
}

That said, I think that a drop-down selection of left, center or right alignment in the custom links widget might be the best option for all users to choose what they prefer. I didn't see anyone else complain though, so it might be just me that has an issue with the fix you made. 
In any case, thanks in advance for the consideration.
