### ISSUE TITLE
Completely broken in version 2.0.2 on Firefox 75

### ISSUE THREAD

**Issue by foxMclion** [joelshepherd/tabliss#217]
- The tab is so slow it shows a black screen for several seconds before showing an image.
- The extension requests images every second frenetically if a timer is selected (request a new image every 15 minutes).

Rolled back to 1.18.2.

**Comment by foxMclion** [comment]
I've also disabled automatic updates to prevent updating to the bad version

**Comment by MaDonghui** [comment]
The custom css rules are applied slowly, visible lag and change

**Comment by MaDonghui** [comment]
firefox Developer Edition 76.0b4
Tabliss 2.0.2

**Comment by Snoobyx** [comment]
Hope you give this one a high priority, it is unusable.

**Comment by joelshepherd** [comment]
> The tab is so slow it shows a black screen for several seconds before showing an image.
This can happen if you are running your browser in private mode. This is because private mode clears Tabliss's cache constantly. Previous Tabliss wouldn't remember any settings in private mode, now it's just the cache.

> The extension requests images every second frenetically if a timer is selected (request a new image every 15 minutes).
Could you try changing this setting and changing it back and seeing if that fixes it? Otherwise I am not able to replicate this, so any help replicating would be appreciated.

> The custom css rules are applied slowly, visible lag and change
Custom CSS applies instantly for me. Which platform are you running (Firefox/Chrome/web)?

**Comment by VFDan** [comment]
Not able to replicate this on my copy of Firefox 75...

**Comment by MaDonghui** [comment]
> Custom CSS applies instantly for me. Which platform are you running (Firefox/Chrome/web)?

I am currently on 
macOS 10.15.4
Firefox Developer Edition 76.0b4

custom css setting is 

```
.Widgets {
padding: 150px
}

.credit {
display: none;
}

.Time {
margin-top: 200px
}

.Overlay {
display: none;
}
```

additionally, I have Time, Message and Quick Link widgets on
This morning the issue is slightly better, but last night in the worst case, the tab was in loading forever, nothing ever appears

**Comment by MaDonghui** [comment]
I restored settings to default and went through settings one by one and discovered the issue
**It is the image blur lagging the entire extension**

Try use Unsplash image, show new photo every new tab, official collection, default Luminosity 
**Increase blur by one unit or above**

see if you can replicate this issue 

Good luck

**Comment by trickypr** [comment]
I can replicate the issues with load time, although the rest of the add-on still feels snappy (firefox 75.0, linux). I can't replicate this issue in brave (chromium) or Gnome Web (webkit).  

This is a [performance bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1596634), and I don't believe there is anything much that we can do to solve it at our end. I will continue to look into this and see if there are any work-arounds I can find.

**Comment by trickypr** [comment]
So, poking around with other stuff related to blurring for something entirely unrelated, I enabled webrender. It turns out that drastically improves performance for blurring.

**Note:** There is a reason why webrender isn't enabled by default on macos and linux. It is because there are other small issues that are slightly annoying. For example, as I am writing this, the text box is changing height by 1 pixel with every key stroke.

## Steps
1. Open the `about:config` page and click the "accept the risk and continue" button.
2. In the search bar search for `gfx.webrender.all` 
3. Press the ![](https://user-images.githubusercontent.com/23250792/83959639-a85cd780-a8c2-11ea-9fc8-3ab0c337c0d8.png) button on the entry for `gfx.webrender.all`.
4. Restart firefox
