### ISSUE TITLE
Make weather display only "feels like" temperature

### ISSUE THREAD

**Issue by lyzhng** [joelshepherd/tabliss#219]
![Screen Shot 2020-04-14 at 5 16 44 PM](https://user-images.githubusercontent.com/23230033/79275194-c0404e00-7e73-11ea-9071-48cf8e8083e8.png)

Is there a way to view _only_ the "feels like" temperature instead of the high and low temps?

**Comment by chaosrun** [comment]
I also prefer the style of the previous weather widget

**Comment by melou-acoss** [comment]
see https://github.com/joelshepherd/tabliss/issues/222

**Comment by DonPascualino** [comment]
I would also appreciate a way to choose if I only want to display the current outside temperature, like the widget looked before. 
I think these two values side by side look weird and unnecessary.

**Comment by chantisnake** [comment]
I think at least make it `<low temp> -- <high temp>` will make things better.

**Comment by dskrepps** [comment]
The *only* metric I want is the current temperature. Seeing the same high and low all day is useless and tells me nothing about when those even are.

**Comment by joelshepherd** [comment]
Unfortunately I had to remove the live weather and swap to a forecast of the day, because the live weather API has started costing me hundreds of dollars per month. As this is a fun side project of mine with no monetisation, that just isn’t something I can afford every month. ☹️

I do get some donations, but that doesn’t cover more than 1/5 of the cost of the API. And since I refuse to ever put ads in Tabliss, I unfortunately had to remove the live weather.

Since so many people have been asking for it back, I was toying with the idea of adding a $1 per month (or some equivalent once-off) option that brings back live weather (and supports the development). But so far I haven't found anyone who wants it back enough to pay for it. 🤷🏻‍♂️

So at this stage I am not looking at bringing the current temperatures back - sorry!
