### ISSUE TITLE
Weather Widget - Temperature range looks odd

### ISSUE THREAD

**Issue by a-wigand** [joelshepherd/tabliss#222]
The temperature range in the weather widget looks like this:
![image](https://user-images.githubusercontent.com/37198703/79307569-63867700-7ef7-11ea-8f60-ce1f6fca602b.png)
The letter spacing is a bit off and I would prefer to read (low - high) instead of (high-low).

**Comment by joelshepherd** [comment]
Hello! I have added some spacing in there for you :)

As for low vs. high first:
I originally had it as (low - high) like you said, but changed it after I realised every other weather app has it around the other way. I think the reason for this is because the high is for the current day, and the low is for the _following_ night. So the high "happens" first, then it transitions to the "low".

At least that's how it looked to me. I will accept any experts in this area to correct me :joy:

**Comment by a-wigand** [comment]
Awesome, thank you for the quick fix!

You are right, the weather apps have it in that order. I can live with that 👍
