### ISSUE TITLE
Tabliss settings problem

### ISSUE THREAD

**Issue by nickbe** [joelshepherd/tabliss#346]
Where are the tabliss settings saved? Are they transfered to your server?

**Comment by nazibalalam** [comment]
You have to manually export them, otherwise **all** settings are stored on encrypted database in firefox. There is no settings file, you have to export them. They are part of the extension otherwise. You can do it like this :- 
![image](https://user-images.githubusercontent.com/69672332/111474577-68caf200-8756-11eb-80d4-d93d8e6e2882.png)

**Comment by CoderOO7** [comment]
> Where are the tabliss settings saved? Are they transfered to your server?

Nope, it uses browser indexDB API to save the data locally on user machine.

**Comment by nickbe** [comment]
We found the problem, thanks. When trying to move a profile folder to another location then several addons seem unconfigured because absolute paths are used here. (Which is not really a good thing and could be avoided)

**Comment by nazibalalam** [comment]
> We found the problem, thanks. When trying to move a profile folder to another location then several addons seem unconfigured because absolute paths are used here. (Which is not really a good thing and could be avoided)

Well, you can export the configurations before moving the profile folder and edit it as per the new path and finally import it after moving the profile folder...

**Comment by nickbe** [comment]
I'm using the loader from portable apps now which is doing the needed changes automatically for addons.
