### ISSUE TITLE
[Request] Bring back custom scripts

### ISSUE THREAD

**Issue by DumbGameMaker** [joelshepherd/tabliss#361]

**Comment by joelshepherd** [comment]
Custom scripts widget still exists, but only for the web version: https://web.tabliss.io/

Unfortunately it cannot come back to the extensions because custom javascript cannot be injected into web extensions because of their content security policy forbids `unsafe-inline`. See the footnote on this page: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy#invalid_examples
