### ISSUE TITLE
Make daily quotes not daily

### ISSUE THREAD

**Issue by Smile4ever** [joelshepherd/tabliss#38]
I would like to have them per-tab, not daily. After a while it gets boring to see the same quote over and over again.

**Comment by CraftyDH** [comment]
@Smile4ever it is possible to create a change interval selection drop down, however They Said So creates daily quotes which means that there is no way to get a new quotes.
However since there are 8 categories it could be possible to implement a cycle feature which starts at the top and changes categories every 3 hours, every hour reusing the first quotes again or just go to the next category each tab opening.
The last thing that could be implemented is using Developer Excuses because their API gives you a random excuse each time.

**Comment by joelshepherd** [comment]
I can't give you "per-tab" because the APIs have strict hourly rate limits. But I have bumped it up to update every hour!
