### ISSUE TITLE
Daily background rotation doesn't work

### ISSUE THREAD

**Issue by arjendk** [joelshepherd/tabliss#44]
I think this is a great extension; it's beautiful and simple and I like being greeted with my name. :-) I'm experiencing this problem however:

I've set the background to Unsplash and "Show a new photo" to daily from the Official collection. However the background never changes; I keep seeing the same background for days. I'm using Tabliss 1.11.2 on Firefox for Linux.

**Comment by arjendk** [comment]
I have had a short look at the source code, without any actual debugging, so I could be wrong, but... could it be that the image timestamp gets inadvertently set to Date.now() sometimes in src/plugins/backgrounds/unsplash/Unsplash.tsx ([here](https://github.com/joelshepherd/tabliss/blob/0924b27c44daf83e8e3b8ce4ff45435422f6d59f/src/plugins/backgrounds/unsplash/Unsplash.tsx#L98))? E.g. at initialisation?

**Comment by joelshepherd** [comment]
Hi, I haven't been able to consistently replicate this issue yet. I have only tested by moving my computer's clock around though, it may be something that only happens when the time naturally passes.

It might be worth noting "daily" is really "24 hours from when the image was first shown". So you could see the same image over 2 days (in the PM of one day and the AM of another). But if your having issues for more days than that its definitely a bug somewhere.

Alternatively there has been a few intermittent issues with the Unsplash API that could also be affecting it.

**Comment by arjendk** [comment]
Thanks for the response. After using the extension for a while, I notice that I often do get a new background now. However I now often suspend the system (with Firefox often still active) instead of restarting. Could that make a difference?

**Comment by joelshepherd** [comment]
I'm closing this as the rotating mechanism has been rewritten for Tabliss 2. Hopefully no more issues!
