### ISSUE TITLE
[Feature request] A button for quick refreshing a new random background

### ISSUE THREAD

**Issue by trmdi** [joelshepherd/tabliss#443]
When you pause changing the background, sometimes you get fed of it and want to change it to another random one.

So it would be nice if there is a small button on the screen to reload it quickly without having to `go to Setting > change "Show a new photo" to something else then back to Pause` many times until you find another nice one.

A shortcut together with that button is even better.

**Comment by noah-curran** [comment]
I'm currently trying to get something like this working. Currently running into a roadblock with interfacing with the data system, as it does not seem (at least on the surface) possible to refresh/change/edit data in the `Backdrop` component (e.g., `Giphy` or `Unslash`) while within the `Overlay` component. What I was thinking of trying was:
1. Add a change background change button to the `on-hover` class of toggles with the icon `refresh-cw`.
2. On click of this button, enforce a new call to the relevant API, serving a new random photo with the relevant tag.

In order to make this call to the API to refresh the image, the current way waits for some defined dependencies/settings to change (for `GIPHY` and `Unslaphed`) or for the timeout to refresh (for `Unsplashed`).
See:
https://github.com/joelshepherd/tabliss/blob/main/src/plugins/backgrounds/unsplash/Unsplash.tsx#L16-L21
https://github.com/joelshepherd/tabliss/blob/main/src/plugins/backgrounds/giphy/Giphy.tsx#L13-L17

I guess something we could try is have a global "refresh" toggle and attach this to the dependency lists, but this seems a bit too hacky... Maybe reentering the same tags to the search field and trick the system into thinking it did actually change may also do the trick, but its unclear if its even possible to touch that data from the perspective of the `Overlay` component. @joelshepherd I'm wondering if the rewrite of the database system makes something like this more possible?

**Comment by joelshepherd** [comment]
Yep, I've added a next (and previous!) button, coming in the next release:

![image](https://user-images.githubusercontent.com/4484306/158832668-f8b2a715-5b05-44e7-8064-e4e8325274d1.png)
