### ISSUE TITLE
Settings are reset after restaring my laptop

### ISSUE THREAD

**Issue by Chromeyyy** [joelshepherd/tabliss#450]
I started using Tabliss a few days go, and I'm lovin it. But for some reason, my settings are reset after restarting my computer.
I'm currently using Brave Browser. Does anyone have any tips on fixing this problem?

**Comment by joelshepherd** [comment]
Hi @Chromeyyy, this has been an issue for a few people. Recently I have been writing a new version beta version of Tabliss to solve this issue, but since I cannot replicate the issue myself, I have had a hard time verifying if it works.

If you would like, could you try testing a beta build and seeing if it resolves your issue?

Here is a previous discussion with instruction on how to use the beta on Firefox: https://github.com/joelshepherd/tabliss/issues/268#issuecomment-1037056557. So follow the same instructions for exporting and uninstalling Tabliss, but then download the Chromium build instead: [tabliss-2.2.0-beta.zip](https://github.com/joelshepherd/tabliss/files/8186304/tabliss-2.2.0-beta.zip). The process of loading an unpacked extension in Brave should be the same as Chrome as far as I know. Extract the zip and [load the unpacked extension.](https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/).

If the beta version works, or even just throws heaps of error messages, I would be keen to hear how it goes!

**Comment by joelshepherd** [comment]
The new release is now out. If you experience any issues after updating, please report them here: https://github.com/joelshepherd/tabliss/issues/459
