### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by azlux** [joelshepherd/tabliss#5]
Hi,
The page load a new picture at every new tab.
It's can use a lot of bandwidth, and it's kind of perturbing.
Do you think it's possible to add a timer to have new image every 1h or 1 day for example ?

Thank
Az

**Comment by joelshepherd** [comment]
Hmm, I can see the bandwidth concerns. I have roadmapped an idea to have a "daily image" background that changes once per day (hopefully to something relevant to the day - think like Google's homepage doodles).

For now though you can "pause" the image rotation for Unsplash by pressing the pause icon in the bottom right. This will stop Tabliss from downloading any new images (and thus not using any bandwidth) until you resume the rotation.

**Comment by Tester798** [comment]
I also would like to see the option to set timer for changing images.
But not because of bandwidth concerns, mostly because some images are too beautiful to be changed right away.

So few options to set period of changing image like `every time`, `every 5 minutes`, `every hour`, `every day` etc would be nice to have.

**Comment by joelshepherd** [comment]
I like the idea of setting the change/refresh interval. I'll see if I can get it in for next release.

**Comment by joelshepherd** [comment]
This feature is now available for Unsplash! 😄 
You should see it in the next day or so when your browser next updates Tabliss.

**Comment by azlux** [comment]
Good Job, look like it's working well !
Thank !
