### ISSUE TITLE
New tab are slow to load

### ISSUE THREAD

**Issue by gagarine** [joelshepherd/tabliss#67]
New tab are quit slow to load. Look like it take ~200ms: The background is white, then black, then the tab load with some kind of fading. Reloading  the tab do the same but without the first white flickr.

I would like to have the tab instantly loaded without fading and flickr. It should be possible because loading a local website is instant (~5ms).

I tried with local image and gradient.

**Comment by joelshepherd** [comment]
I am not sure what exactly I can do to speed up the initial white flash, that's pretty much the browsers opening the local index page. Unless I have Tabliss fade from white instead of black.

Once the screen goes black, Tabliss has taken over. Form here the browsers need to parse that JavaScript, then load your setting from the local IndexedDB. When you have a large number of images (and especially cached GIFs), it can take a little bit to pull everything from the database. If resetting your settings to default fixes the load issue, it usually this. A strategy I have been thinking of implementing is lazy loading cached assets after settings, but if you have few cached assets, the extra latency of 2 sequential calls could slow the initial load down time of the assets that needs to be displayed, more than just loading all assets the first time.

A fun fact (probably related to above), is in Chrome. When you open a new tab when none of your other tabs are displaying Tabliss, it flickers a little (and is a touch slow) on load. But when you have Tabliss open in one of your other tabs, then open a new one, Tabliss will load much quicker this time. I wonder if its because the browsers already has the IndexedDB database open and in memory. I have though about using this to my advantage and having a background page that keeps the IndexedDB database open at all times for faster loading, but it will probably add memory overhead.

Ironically, because of the service worker, the web version actually loads faster than the local extension version! (Try refreshing the web version vs. the extension). I am not sure if I can utilise service workers as an extension. Or why that would even be faster than a local file?

**Comment by gagarine** [comment]
1) perhaps removing the fading (optionally) 
2) We need an API to set the background color of a new tab should be  before the script is loaded
3) If 2 is not possible, perhaps avoid the solid lack background (I'm guessing it's in the loaded CSS) before the fading (I'm having a color gradient) can improve the load feeling.

I'm really speaking about perception, it's not a big lag. Perhaps some stuff like 2 need to be fixed upstream. But When I click "new tab" I want a new tab loaded and ready ;).

An option for Firefox would be to always have a new tab ready but hidden, and show it when the user click on newtab.

**Comment by joelshepherd** [comment]
The storage layer (the primary source of slowness) was rewritten in Tabliss 2. Can anyone confirm if Tabliss feels snappier in version 2?

**Comment by Smile4ever** [comment]
@joelshepherd It does. But the fact that tabliss has a black background and Firefox a white one by default makes it annoying. Can I set the default background color for Tabliss to white using custom CSS?

**Comment by a-rock-lobster** [comment]
Like @Smile4ever, I have been trying to work out whether I can change the black background so as to fade from white.

**Comment by joelshepherd** [comment]
I've added a feature that will set the fade in colour based on whether you had a light or dark "theme".

Currently this only works with backgrounds that support the luminosity display property (like Unspash), but I will implement a proper theme selector next big update.
