### ISSUE TITLE
Blur Background

### ISSUE THREAD

**Issue by dauntedvariable** [joelshepherd/tabliss#71]
A blurred background should offer better text visibility in comparison to a slightly darkened one which usually does not have much effect for images with light colours.

**Comment by trickypr** [comment]
To do this you will need to remove the `background-color` of `.Dashboard`, `.App`, and `.root`. You will also have to remove the following code from `.Unsplash`:
```css 
background-position: 50% 50%;
background-size: cover;
transition: opacity .25s ease-out;
```
Then you will need to add the following code to `.Unsplash::before`:
```css
content: "";
position: fixed;
left: -5%;
top: -5%;
right: 0;
z-index: -1;
display: block;
background-size: cover;
width: 110%;
height: 110%;
filter: blur(5px); /* Change this to change the amount of blur */
```
Then when applying the image you need to apply it to `.Unsplash::before` instead of `.Unsplah`. 
There may be a simpler way to do this but this is what I found works. I hope it is helpful.

**Comment by joelshepherd** [comment]
This is now in Tabliss :)
