### ISSUE TITLE
Doing a search whilst in full screen mode exits full screen mode

### ISSUE THREAD

**Issue by odebroqueville** [joelshepherd/tabliss#75]
I'm not certain this is a bug, but I think it would be nicer if doing a search whilst in full screen mode would display the search results in full screen instead of exiting full screen mode. I had selected the search widget and entered full screen mode using the icon in the top left hand corner. A part from that, I'd just like to say that this extension is progressing in a nice way. Congratulations for the good work! Keep it up.

**Comment by PeteS7N** [comment]
It's not a bug. When you enter the full screen mode using the icon, you are actually entering _document_'s full screen mode (i.e. requesting fullscreen under _document_ element, in other words, displaying content of HTML page in fullscreen), but this **doesn't switch the browser to fullscreen**. And when you leave that _document_ (Tabliss extension new tab page), you are also leaving that _document_'s fullscreen mode.

However, this can be probably solved by simulating a press of "F11" button.

Or you can just enter your browser's full screen mode and then try to search from the extension, it should work and you would stay in the full screen mode. 😉

**Comment by odebroqueville** [comment]
On macOS High Sierra, Ctrl+Cmd+F toggles full screen mode for the browser app, but Shift+Cmd+F is what I was looking for. It would be rather cool, if doing a search in (HTML document) full screen mode would open the results in (HTML document) full screen mode. Actually, in Chrome on macOS, there does appear to be a bug because Shift+Cmd+F doesn't work after I open a new tab.
[Keyboard shortcuts](https://www.w3schools.com/TAGs/ref_keyboardshortcuts.asp)

**Comment by joelshepherd** [comment]
I took a little look around, and while I was sure I couldn't do this, apparently I can. The web extensions API does indeed have a way to make the entire browser window fullscreen, as opposed to just the Tabliss document.

Its not perfect though, as there is no "returning" from this fullscreen mode, I kinda of just choose whether you come back as a regular or maximised window. I could save what it was before it went fullscreen, but then that would be lost if you went off browsing the internet because returning to tabliss.

It also doesn't let you just press "escape" to leave this fullscreen. So someone might get lost in fullscreen mode if they leave Tabliss via search results, not knowing how to get back to normal windowed mode :joy:

The main question then is whether the fullscreen button in Tabliss should make Tabliss fullscreen, or the entire browser fullscreen? I am probably leaning towards the existing functionality, instead recommending the built in fullscreen keyboard shortcut instead to get that full fullscreen experience 😎. That way you wouldn't get surprise-stuck in fullscreen, because you would know the shortcut!

**Comment by odebroqueville** [comment]
@joelshepherd "...as there is no "returning" from this fullscreen mode..." Cmd + Ctrl + F on macOS (not sure what the equivalent is on Windows or Linux), which does the same as clicking on the green dot in the top left hand corner of a window, should toggle in and out of full-screen mode. The funny thing is that, opening a new tab, you'll still see expanding arrows icon to maximising the browser document. This will have the effect of completely hiding the browser chrome. The Esc key will get you out, but you'll still need to use Cmd + Ctrl + F to exit window full-screen mode.

The advantage of the window full-screen mode (Cmd + Ctrl + F) over document full-screen mode is that it is persistent, so if you do a search using the search widget you'll stay in full-screen mode. So the remaining question to me is if it's possible to associate the Esc key to Cmd + Ctrl + F (or it's equivalent on Windows or Linux) to exit window full-screen mode.

**Comment by CraftyDH** [comment]
@joelshepherd you could make it so that the button activates a function in the extension which would then allow the extension to use a keyboard handler to search for "Escape" key to then take it out of full screen mode.

**Comment by joelshepherd** [comment]
I did forgot about this issue. I think I'll leave the full screen mode as document-based, and not interfere with the browser's main full screen controls.
