### ISSUE TITLE
Vimium keyboard shortcuts

### ISSUE THREAD

**Issue by jcrben** [joelshepherd/tabliss#88]
Apparently extensions have trouble running on new tabs. Vimium and other extensions have issues on Chrome due to this and so opening a new tab doesn't enable their keyboard shortcuts.

Currently I'm using the extension suggested at https://github.com/philc/vimium/issues/2845#issuecomment-348117748 (there's also https://github.com/philc/vimium/issues/2845#issuecomment-349904212 - another extension) to retain my vimium keyboard shortcuts.

Any ideas on how to use this while retaining my default vimium keyboard shortcuts? If not, no worries - feel free to close this issue if it's not in scope. Someday perhaps I'll try digging into the code anyhow, but probably not anytime soon.

**Comment by joelshepherd** [comment]
4 years later sorry, not within Tabliss sorry. You could try redirecting your new tab page to the [web version](http://web.tabliss.io) somehow, and that would work?

**Comment by nanoraptor** [comment]
I would really love this feature to be integrated. The reason why we switch to these custom tab extensions is because they should offer things that the normal ones doesn't. It should offer customization that the default one doesn't. I would say tabliss does that part very well. But, not with other extensions working with tabliss. Like vimium. 

> 4 years later sorry, not within Tabliss sorry. You could try redirecting your new tab page to the [web version](http://web.tabliss.io) somehow, and that would work?

can we atleast know why?

**Comment by CuboidRaptor** [comment]
I may be wrong, but I have tried to make Vimium work on extension new tab pages and I think it honestly just doesn't like them (not just tabliss)
firefox has security policies that prevent it from being possible (or at least, very difficult)
