### ISSUE TITLE
Custom JS snippet blocked by CSP

### ISSUE THREAD

**Issue by natsuozawa** [joelshepherd/tabliss#90]
The custom JS snippet fails to be inserted because of Content Security Policy.

Steps to reproduce:
1. Add Custom JS
2. Take a look at the browser's console

I have tried this on both Firefox and Chrome, on Windows 10 and Ubuntu without success.
The web version doesn't seem to have the problem.

Error on Firefox 62.0.2 (64 bit):
![image](https://user-images.githubusercontent.com/28969934/45949480-f40c1680-c036-11e8-9d30-d4384d0f6f44.png)

Error on Chrome 69.0.3497.100 (Official Build) (64-bit):
![image](https://user-images.githubusercontent.com/28969934/45949563-3df4fc80-c037-11e8-97d6-c903893f24ae.png)

I can try to make a pull request for this if that is welcomed!

**Comment by joelshepherd** [comment]
That will teach me to dev using the web version mostly 🤦‍♂️ 

In the web extensions docs, it seems you cannot allow inline scripts in the extensions CSP. And while is says at the bottom of [this page](https://developer.chrome.com/extensions/contentSecurityPolicy) inline scripts created from content scripts should work, unfortunately I do not believe the scripts included in the new tag page count as content scripts.

So the workaround here would be to generate a unique nonce, hardcore it into the extensions content security policy, and add the nonce to the injected script tag. Although having a hardcoded nonce does defeat half the point of a CSP, I cannot see any other way to make it happen.

If you can get that working, I will be happy to accept a PR. Otherwise I might get some time next week I can look into it!

**Comment by nralbrecht** [comment]
I tried solving this problem and got it to work again. I injected the code with the [`tabs.executeScript`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/Tabs/executeScript) function like this:
```javascript
private attach() {
  if (process.env.BUILD_TARGET === 'web') {
    // the old approach
  } else {
    browser.tabs.executeScript({
      allFrames: false,
      code: this.props.input || ''
    });
  }
}
```

The problem with this is, that the injected script has access to the WebExtention API's. In [Chrome](https://developer.chrome.com/extensions/content_scripts#capabilities) and [Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#WebExtension_APIs) content script's only have restricted access to the API's. 

Do you think we should try to sandbox this in some way? I could think of overwriting all variables locally, like: 
```javascript 
code: '(function() { let browser = window.browser = undefined; ' + (this.props.input || '') + '})();'
```
Maybe we could reject all code snippets that contain e.g. browser.

I guess my ideas are not particularly robust. What do you think?

Nils

**Comment by joelshepherd** [comment]
Huh, I didn't even think to try the tabs API. Even in its restricted form (not being able to use the web extension APIs), it would be useful for many other functions (making `fetch()` calls, etc).

I'll definitely investigate this further.

**Comment by nralbrecht** [comment]
I had a nother look at the capabilities of content script's. I found two possibly dangerous API's:
1. XMLHttpRequest / fetch
    - requesting any webpage due to privileged scope
2. [runtime.connect()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/connect)
    - communicate with message channels with possibly sensitive data

I think it would be reasonable to give the user this control, hence I could think of a couple uses for this. But we should display a proper warning along the lines of `Please make sure you know what you are doing, otherwise security vulnerabilities may occur.`

If you ok with this, I am happy to make a pull request with this.

**Comment by natsuozawa** [comment]
Apologies for the inactivity. I believe that the tabs API is an adequate solution for this problem. 

I find the possible security risks that @nralbrecht has mentioned are acceptable.
Considering that this is a user-generated script on a local extension, this doesn't sound too problematic.

The current situation of user-generated scripts not working at all is a bit disappointing, so this kind of fix even as a short term solution will be appreciated.

**Comment by amelekhin** [comment]
Any updates on this one? Would love to use custom JS with this extension.

**Comment by nralbrecht** [comment]
I totally forgot about this.
I'm quite busy at the moment but I will continue to work on this next week.

**Comment by joelshepherd** [comment]
The conclusion here was the Firefox review team does not allow arbitrary code execution within extensions, so the Custom JS plugin will remain only available in the web version. A few more details are in the PR.

Sorry guys!

**Comment by nralbrecht** [comment]
Thanks for trying. I guess their restrictions around arbitrary code execution are somewhat reasonable. A shame that there is no proper sandboxed way around this.
