### ISSUE TITLE
settings lost in new container tabs

### ISSUE THREAD

**Issue by unhammer** [joelshepherd/tabliss#92]
When I open a new/different container tab, I get "fresh" tabliss settings from the ones in "uncontainered" tabs.

**Comment by CraftyDH** [comment]
@unhammer It would not be possible because the nature of "containers" is to separate cookies, therefore it would be impossible for tabliss to access the settings from another container.
![image](https://user-images.githubusercontent.com/23249291/48250693-43759d00-e453-11e8-924e-3b4470572666.png)
However a json save/import could be implemented to quickly copy settings over.

**Comment by trickypr** [comment]
The reason why you lose data when changing over containers is the way that tabliss is because settings are stored in IndexDB. The problem with IndexDB is that the add-on can't assess it from one container to another. Other add-ons use the [WebExtensions storage API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage). There are a multitude of problems with using WebExtension apis, the most obvious is that they are not accessible to standard websites, meaning there would have to be a separation between the code for [web.tabliss.io](https://web.tabliss.io/) and the main add-on. There is currently a related discussion going on in #69.

**Comment by dnut** [comment]
> there would have to be a separation between the code for web.tabliss.io and the main add-on

Who cares? I can't imagine why someone would use web.tabliss.io if they have the extension. Consistency between different container tabs should be a much higher priority.

Besides, sharing settings between the addon and the website doesn't even work unless you have third party cookies enabled, which is a privacy and security liability. For now this is the default in Firefox, but typically anyone with a remote interest in privacy disables it. Google actually plans to disable all third party cookie access in Chrome, and I expect Firefox to follow suit.

> There is currently a related discussion going on in #69.

Yet another example of IndexedDB being a poor choice.

**Comment by joelshepherd** [comment]
IndexedDB was originally chosen because it can quickly store entire image blobs without needing to encode first. I can't remember the exact numbers now, but Tabliss would boot 2-3x faster when using IndexedDB compared to the extension storage (which was based on localStorage).

However this has since changed with recent versions of browsers switching the internals of extension storage over to IndexedDB under the hood. As such I have rewritten the storage in Tabliss 2 to take advantage of this. So if all went well, Tabliss show now support containers :tada:

**Comment by manuel-garnier** [comment]
Hello,
This was working fine before 2.* release, having separate settings for each container.
This is no longer the case since update and migration from second container erases settings from the first migrated one.
Currently, settings seem to be shared between all containers. Any modification to one container is applied in others when tab is refreshed.

I'm using a portable Firefox version (via PortableApps).
Is there any way to recover last settings before migration or do you have erased them completely?
Thanks,
New version seems great though, even though my new configuration has been lost too :(

**Comment by manuel-garnier** [comment]
> Hello,
> This was working fine before 2.* release, having separate settings for each container.
> This is no longer the case since update and migration from second container erases settings from the first migrated one.
> Currently, settings seem to be shared between all containers. Any modification to one container is applied in others when tab is refreshed.
> 
> I'm using a portable Firefox version (via PortableApps).
> Is there any way to recover last settings before migration or do you have erased them completely?
> Thanks,
> New version seems great though, even though my new configuration has been lost too :(

Hello again!
I guess I misunderstood the original problem of this thread, especially your last comment:
> Tabliss show now support containers 🎉.

Prior 2.+ releases, I took advantage of that containerization to have a different profile for each container...
However, described behavior during migration is still wrong to me, because some data is lost.
You could add a note in Warning message about multiple tabliss configurations (because of containers) or try to merge with new 2.+ config if one is already found in new storage location?

Anyway, it was not an easy task (due to IndexDB I was only discovering...), I managed to get back my original Tabliss configs (from a saved unusable profile, more fight with corrupted IndexDB...). Glad it's just plain json now 😅 instead of a hard to decode blob. I finally merged my different Tabliss configs into a single one.
